name: guardian
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text:
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  font_awesome_flutter:
  intl:
  page_transition:
  timeago:
  url_launcher:
  mqtt_client: ^9.6.1
  provider:
  http: ^0.13.3
  flutter_bloc: ^7.0.1
  fluttertoast: 8.0.8
  json_path: ^0.3.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.7
  flutter_local_notifications: ^9.5.3
  stop_watch_timer: ^1.3.1
  syncfusion_flutter_sliders: ^19.3.54
  #sip_ua: ^0.4.0

  #voip
  get:
  hive:
  hive_flutter:
  path_provider:
  uuid:
  marquee_widget:
  flutter_dialpad:
  contacts_service:
  permission_handler: ^8.3.0
  country_code_picker:
  intent:
  #native_contact:
  sqflite:
  jiffy:
  flutter_background_service: ^1.0.0
  google_fonts: ^2.2.9
  flutter_linkify: ^5.0.2
  webview_flutter: ^3.0.4
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
