///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginRequest {
/*
{
  "password": "string",
  "username": "string"
}
*/

  String? password;
  String? username;

  LoginRequest({
    this.password,
    this.username,
  });
  LoginRequest.fromJson(Map<String, dynamic> json) {
    password = json['password']?.toString();
    username = json['username']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['password'] = password;
    data['username'] = username;
    return data;
  }
}
