///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginResponse {
/*
{
  "status": true,
  "message": ""
}
*/

  bool? status;
  String? message;

  LoginResponse({
    this.status,
    this.message,
  });
  LoginResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    return data;
  }
}
